name: build clay example

description: build clay example

runs:
  using: composite
  steps:
    - name: Install Common Dependencies
      uses: ./lynx/.github/actions/common-deps
      with:
        target: 'clay'
    - name: Build Clay Example
      shell: bash
      run: |-
        cd $GITHUB_WORKSPACE/lynx
        source tools/envsetup.sh
        buildtools/gn/gn gen out/Default --args='enable_clay_standalone = true disable_visibility_hidden = true use_ndk_static_cxx = false enable_linker_map = false enable_clay = true is_headless = true skia_enable_flutter_defines = true skia_use_dng_sdk = false skia_use_sfntly = false skia_enable_pdf = false skia_enable_svg = true enable_svg = true skia_enable_skottie = true skia_use_x11 = false skia_use_wuffs = true skia_use_expat = true skia_use_fontconfig = false clay_enable_skshaper = true skia_use_icu = true skia_gl_standard = "" allow_deprecated_api_calls = true stripped_symbols = true is_official_build = true is_debug = false use_clang_static_analyzer = false enable_lto = false use_flutter_cxx = false' --export-compile-commands
        buildtools/ninja/ninja -C out/Default clay/example/glfw
