name: install common dependencies

description: pull common source and binary dependencies via habitat.

inputs:
  concurrency:
    description: concurrency of requests
    default: '2'
    required: false
  cache-backend:
    description: cache backend for habitat
    default: 'lynx-infra'
    required: false
  target:
    description: habitat target
    default: ''
    required: false
  # actions/cache stores files with relative directory, which causes inconsistency between self-hosted runner and
  # container runner. Therefore, add this temporary option to modify cache key prefix as a workaround. Delete this when
  # we are able to adjust the container runner's directory structure to the same as self-hosted runner.
  cache-key-prefix:
    description: cache key prefix for cache action
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: Get habitat cache key
      id: hab
      shell: bash
      run: |
        which python3
        if [[ "${{ inputs.target }}" == "" ]]; then
          python3 lynx/tools/ci/habitat_cache_helper.py
        else
          python3 lynx/tools/ci/habitat_cache_helper.py --target ${{ inputs.target }}
        fi

    - name: Setup cache action
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ~/.habitat_cache
        key: hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-${{ steps.hab.outputs.HABITAT_DEPS_FILE_DIGEST }}
        restore-keys: |
          hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-

    - name: Setup cache action
      if: ${{ inputs.cache-backend == 'github' }}
      uses: actions/cache@v4
      with:
        path: ~/.habitat_cache
        key: hab-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-${{ steps.hab.outputs.HABITAT_DEPS_FILE_DIGEST }}
        restore-keys: |
          hab-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-

    - name: Get Python Cache Directory
      id: pip
      shell: bash
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      run: echo "PIP_CACHE_DIR=$(python3 -m pip cache dir)" >> $GITHUB_OUTPUT

    - name: Python Requirements Cache
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ${{ steps.pip.outputs.PIP_CACHE_DIR }}
        key: pip${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ hashFiles('lynx/tools/vpython_tools/requirements.txt', 'lynx/testing/integration_test/test_script/requirements.txt') }}
        restore-keys: |
          pip${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    - name: Cache pnpm Dependencies
      if: ${{ inputs.cache-backend == 'lynx-infra' && inputs.cache-key-prefix == '' }}
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        # set pnpm store path to a specific value since we can't get it via `pnpm store path` before pnpm is setup.
        path: ~/.local/share/pnpm/store
        key: pnpm-${{ runner.os }}-${{ hashFiles('lynx/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ runner.os }}-

    - name: Install Python dependencies
      uses: nick-fields/retry@v3
      with:
        max_attempts: 3
        retry_wait_seconds: 3
        timeout_minutes: 20
        command: |
          set -e
          which python3
          if [ "$RUNNER_OS" == "macOS" ]; then
            python3 -m pip install -r lynx/tools/vpython_tools/requirements.txt --break-system-packages --retries 10 --timeout 60
            python3 -m pip install -r lynx/testing/integration_test/test_script/requirements.txt --break-system-packages --retries 10 --timeout 60
          else
            python3 -m pip install -r lynx/tools/vpython_tools/requirements.txt --retries 10 --timeout 60
            python3 -m pip install -r lynx/testing/integration_test/test_script/requirements.txt --retries 10 --timeout 60
          fi

    - name: run habitat sync
      shell: bash
      working-directory: lynx
      run: |
        if [[ "${{ inputs.target }}" == "" ]]; then
          tools/hab sync .
        else
          tools/hab sync . --target ${{ inputs.target }}
        fi
      env:
        HABITAT_CONCURRENCY: ${{ inputs.concurrency }}
        npm_config_store_dir: ~/.local/share/pnpm/store
