name: CocoaPods Token Keepalive

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  token-keepalive:
    runs-on: lynx-darwin-15.6.1-medium
    env:
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          path: lynx
      - name: Setup Ruby Cache
        uses: ./lynx/.github/actions/ios-common-deps
        with:
          cache-backend: 'lynx-infra'
      - name: Keep CocoaPods Token alive
        run: |
          cd $GITHUB_WORKSPACE/lynx
          SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk bundle install --path .bundle
          bundle exec pod trunk me --silent
